package org.eclipse.scout.apps.contactscout.shared.common;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

import javax.annotation.Generated;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.apps.contactscout.client.common.AbstractUrlImageField", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractUrlImageFieldData extends AbstractFormFieldData {
    private static final long serialVersionUID = 1L;

    /**
     * access method for property Url.
     */
    public String getUrl() {
        return getUrlProperty().getValue();
    }

    /**
     * access method for property Url.
     */
    public void setUrl(String url) {
        getUrlProperty().setValue(url);
    }

    public UrlProperty getUrlProperty() {
        return getPropertyByClass(UrlProperty.class);
    }

    public static class UrlProperty extends AbstractPropertyData<String> {
        private static final long serialVersionUID = 1L;
    }
}
