package org.eclipse.scout.apps.contactscout.shared.common;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

import javax.annotation.Generated;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.apps.contactscout.client.common.AbstractNotesBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractNotesBoxData extends AbstractFormFieldData {
    private static final long serialVersionUID = 1L;

    public Notes getNotes() {
        return getFieldByClass(Notes.class);
    }

    /**
     * access method for property Notes.
     */

    /**
     * access method for property Notes.
     */
    public void setNotes(String notes) {
        getNotesProperty().setValue(notes);
    }

    public NotesProperty getNotesProperty() {
        return getPropertyByClass(NotesProperty.class);
    }

    public static class Notes extends AbstractValueFieldData<String> {
        private static final long serialVersionUID = 1L;
    }

    public static class NotesProperty extends AbstractPropertyData<String> {
        private static final long serialVersionUID = 1L;
    }
}
